### PR TITLE
Run CI on pre-release

### PR DESCRIPTION
**Pull request by gdalle**
Create a matrix of Julia versions for CI, containing `1` and `pre`

### CODE REVIEW

**Comment by willtebbutt** [comment]
This definitely won't work currently, because the way that `Array`s work changed substantially in 1.11. We've still got your open issue about this -- once I've had the time to address that, I'll enable CI for pre-releases.

**Comment by gdalle** [comment]
My bad, I just opened this because I noticed that I wasn't testing Mooncake on 1.11 in DI and I wondered why

**Comment by willtebbutt** [comment]
Ahh okay, np at all.

**Comment by willtebbutt** [comment]
I'm going to close this, as I'm working on a separate PR to address the various things that need addressing for 1.11 at the minute.

**Pull request closed without merging**
